-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Sample_pb')


SAMPLE = protobuf.Descriptor();
local SAMPLE_ID_FIELD = protobuf.FieldDescriptor();
local SAMPLE_MSG_FIELD = protobuf.FieldDescriptor();

SAMPLE_ID_FIELD.name = "id"
SAMPLE_ID_FIELD.full_name = ".Sample.id"
SAMPLE_ID_FIELD.number = 1
SAMPLE_ID_FIELD.index = 0
SAMPLE_ID_FIELD.label = 2
SAMPLE_ID_FIELD.has_default_value = false
SAMPLE_ID_FIELD.default_value = 0
SAMPLE_ID_FIELD.type = 5
SAMPLE_ID_FIELD.cpp_type = 1

SAMPLE_MSG_FIELD.name = "msg"
SAMPLE_MSG_FIELD.full_name = ".Sample.msg"
SAMPLE_MSG_FIELD.number = 2
SAMPLE_MSG_FIELD.index = 1
SAMPLE_MSG_FIELD.label = 1
SAMPLE_MSG_FIELD.has_default_value = false
SAMPLE_MSG_FIELD.default_value = ""
SAMPLE_MSG_FIELD.type = 9
SAMPLE_MSG_FIELD.cpp_type = 9

SAMPLE.name = "Sample"
SAMPLE.full_name = ".Sample"
SAMPLE.nested_types = {}
SAMPLE.enum_types = {}
SAMPLE.fields = {SAMPLE_ID_FIELD, SAMPLE_MSG_FIELD}
SAMPLE.is_extendable = false
SAMPLE.extensions = {}

Sample = protobuf.Message(SAMPLE)

